#
# User configuration sourced by login shells
#
# Author:  Benjamin Rau
# License: MIT

# Startx when loging in on first vt.
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx

# Initialize zim
[[ -s ${ZIM_HOME}/login_init.zsh ]] && source ${ZIM_HOME}/login_init.zsh
