export XKB_DEFAULT_LAYOUT=us
export XKB_DEFAULT_VARIANT=altgr-intl
export XKB_DEFAULT_OPTIONS=caps:escape
export TERMINAL=alacritty
export WLR_DRM_NO_MODIFIERS=1

PATH="$HOME/.yarn/bin:$PATH"
PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
