# Become famous. Write history.
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=5000
# No need to type cd.
setopt autocd

export TERMINAL

# Load useful functions.
source $HOME/.zsh/helper_functions.zsh

# Aliases to save some time.
source $HOME/.zsh/alias.zsh

# Per machine configuration.
source $HOME/.zsh/personal.zsh

# Load all exports
source $HOME/.zsh/exports.zsh

# Load autocompletion stuff.
source $HOME/.zsh/completion.zsh

DEFAULT_USER=benjamin

# Load plugins.
source $HOME/.zsh/plugins.zsh

# Use vim edit mode.
bindkey -v
# Set keytimeout to 0.1s for faster switching between insert/command mode.
export KEYTIMEOUT=1
# Set up reverse search in vi mode.
bindkey '^R' history-incremental-search-backward
